// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJkKO7vmd2LJ2_kPkIOI_J-AbzEZ_8_NM',
    appId: '1:259370708796:android:6f07d2fbd449d389a2b839',
    messagingSenderId: '259370708796',
    projectId: 'ai-study-pal',
    databaseURL: 'https://ai-study-pal-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ai-study-pal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2tHuFcA4p7kngd8QtDCGHTn2BzlvB88o',
    appId: '1:259370708796:ios:ebf70f596d7ed92ba2b839',
    messagingSenderId: '259370708796',
    projectId: 'ai-study-pal',
    databaseURL: 'https://ai-study-pal-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ai-study-pal.appspot.com',
    androidClientId: '259370708796-85svumtsgeh8nc6svrer57q4cvuaea7i.apps.googleusercontent.com',
    iosClientId: '259370708796-7i22in18g3epme5tk7q01th2hmp0qblu.apps.googleusercontent.com',
    iosBundleId: 'com.example.summarizeApp',
  );
}
